use_frameworks!

platform :ios, '8.0'

target 'LGSpecialTrainingFramework_Example' do
  pod 'LGSpecialTrainingFramework', :path => '../'

  target 'LGSpecialTrainingFramework_Tests' do
    inherit! :search_paths

    
  end
end
